server:
  port: 8060


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

#Actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
      enabled: true
    enabled-by-default: false

#zipkin
spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

